# Generated by Django 5.2.8 on 2025-11-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postattachment',
            options={},
        ),
    ]
